#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Patrick Young

# This script should only be used in OpenWRT
# Clash Path is /sbin/clash

START=95
STOP=15
USE_PROCD=1

start_service(){
    procd_open_instance
    procd_set_param command /sbin/clash
    procd_append_param command -d /root/.config/clash
    procd_set_param file /root/.config/clash/config.yaml
    procd_set_param respawn 600 15 3
    procd_set_param stdout 0    # this should change to 1 for debugging purpose
    procd_set_param stderr 0    # same as above
    procd_set_param user root
    procd_set_param pidfile /var/run/clash.pid
    [ -e /proc/sys/kernel/core_pattern ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance

    # TCP Redirection
    iptables -t nat -w -N clash
    # # Bypass LAN
    iptables -t nat -w -A clash -d 0.0.0.0/8 -j RETURN
    iptables -t nat -w -A clash -d 10.0.0.0/8 -j RETURN
    iptables -t nat -w -A clash -d 100.64.0.0/10 -j RETURN
    iptables -t nat -w -A clash -d 127.0.0.0/8 -j RETURN
    iptables -t nat -w -A clash -d 169.254.0.0/16 -j RETURN
    iptables -t nat -w -A clash -d 172.16.0.0/16 -j RETURN
    iptables -t nat -w -A clash -d 192.168.0.0/16 -j RETURN
    iptables -t nat -w -A clash -d 224.0.0.0/4 -j RETURN
    iptables -t nat -w -A clash -d 240.0.0.0/4 -j RETURN
    iptables -t nat -w -A clash -d 255.255.255.255/32 -j RETURN
    iptables -t nat -w -A clash -p tcp -j REDIRECT --to-port 17894
    # Apply Rules
    iptables -t nat -w -A PREROUTING -j clash
    iptables -t nat -w -A OUTPUT -p tcp -d 198.18.0.0/16 -j REDIRECT --to-port 17894
    # UDP Redirection
    ip rule add fwmark 1 table 100
    ip route add local 0.0.0.0/0 dev lo table 100
    iptables -t mangle -w -N clash_mask
    iptables -t mangle -w -A clash_mask -d 0.0.0.0/8 -j RETURN
    iptables -t mangle -w -A clash_mask -d 10.0.0.0/8 -j RETURN
    iptables -t mangle -w -A clash_mask -d 100.64.0.0/16 -j RETURN
    iptables -t mangle -w -A clash_mask -d 127.0.0.0/8 -j RETURN
    iptables -t mangle -w -A clash_mask -d 169.254.0.0/16 -j RETURN
    iptables -t mangle -w -A clash_mask -d 172.16.0.0/16 -j RETURN
    iptables -t mangle -w -A clash_mask -d 192.168.0.0/16 -j RETURN
    iptables -t mangle -w -A clash_mask -d 224.0.0.0/4 -j RETURN
    iptables -t mangle -w -A clash_mask -d 240.0.0.0/4 -j RETURN
    iptables -t mangle -w -A clash_mask -d 255.255.255.255/32 -j RETURN
    iptables -t mangle -w -A clash_mask -p udp -j TPROXY --on-port 17894 --tproxy-mark 1
    iptables -t mangle -w -A OUTPUT -p udp -d 198.18.0.0/16 -j MARK --set-mark 1
    iptables -t mangle -w -A PREROUTING -p udp -j clash_mask
    # DNS Options
    iptables -t nat -w -N clash_dns
    iptables -t nat -w -A clash_dns -p udp -j REDIRECT --to-port 10053
    iptables -t nat -w -I OUTPUT -p udp --dport 53 -j clash_dns
    iptables -t nat -w -I PREROUTING -p udp --dport 53 -j REDIRECT --to 10053
}

stop_service(){
    local clash_mpid=""

    clash_mpid=$(ps -w | grep -w "/sbin/clash" | grep -v grep| awk '{print $1}')
    
    if [ "${clash_mpid}" != "" ]; then
        kill -9 ${clash_mpid}
    fi

    # Clean out PIDFile
    rm -f /var/run/clash.pid
    # Clean FWMARK
    ip rule del fwmark 1 table 100
    ip route del local 0.0.0.0/0 dev lo table 100
    # Delete Reference First
    iptables -t nat -w -D PREROUTING -j clash
    iptables -t mangle -w -D PREROUTING -j clash_mask
    iptables -t nat -w -D OUTPUT -p tcp -d 198.18.0.0/16 -j REDIRECT --to-port 17894
    iptables -t mangle -w -D OUTPUT -p udp -d 198.18.0.0/16 -j MARK --set-mark 1
    iptables -t mangle -w -D PREROUTING -p udp -j clash_mask
    iptables -t nat -w -D OUTPUT -p udp --dport 53 -j clash_dns
    iptables -t nat -w -D PREROUTING -p udp --dport 53 -j REDIRECT --to 10053
    # Clear all rules
    iptables -t mangle -w -F clash_mask
    iptables -t nat -w -F clash
    iptables -t nat -w -F clash_dns
    # Delete created chains
    iptables -t mangle -w -X clash_mask
    iptables -t nat -w -X clash
    iptables -t nat -w -X clash_dns
}
