#!/bin/sh /etc/rc.common
# Copyright (C) 2020 Patrick Young

# This script should only be used in OpenWRT
# Clash Path is /sbin/clash

START=95
STOP=15
USE_PROCD=1

start_service(){
    procd_open_instance
    procd_set_param command /sbin/clash
    procd_set_param file /root/.config/clash/config.yaml
    procd_set_param respawn 600 15 3
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user root
    procd_set_param pidfile /var/run/clash.pid
    [ -e /proc/sys/kernel/core_pattern ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance

    # Add Redirection (DNS Hijacking)
    iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
    iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
    # Add Forward
    ip rule add fwmark 1 table 100
    ip route add local 0.0.0.0/0 dev lo table 100
    iptables -t mangle -N clash
    # # Bypass LAN
    iptables -t mangle -A clash -d 0.0.0.0/8 -j RETURN
    iptables -t mangle -A clash -d 10.0.0.0/8 -j RETURN
    iptables -t mangle -A clash -d 100.64.0.0/16 -j RETURN
    iptables -t mangle -A clash -d 127.0.0.0/8 -j RETURN
    iptables -t mangle -A clash -d 169.254.0.0/16 -j RETURN
    iptables -t mangle -A clash -d 172.16.0.0/16 -j RETURN
    iptables -t mangle -A clash -d 192.168.0.0/16 -j RETURN
    iptables -t mangle -A clash -d 224.0.0.0/4 -j RETURN
    iptables -t mangle -A clash -d 240.0.0.0/4 -j RETURN
    # # Proxy all devices on lan
    iptables -t mangle -A clash -p udp -j TPROXY --on-port 17894 --tproxy-mark 1
    iptables -t mangle -A clash -p tcp -j TPROXY --on-port 17894 --tproxy-mark 1
    # Apply Rules
    iptables -t mangle -A PREROUTING -j clash
    # # Proxy Gateway Itself
    iptables -t mangle -N clash_mask
    iptables -t mangle -A clash_mask -d 0.0.0.0/8 -j RETURN
    iptables -t mangle -A clash_mask -d 10.0.0.0/8 -j RETURN
    iptables -t mangle -A clash_mask -d 100.64.0.0/16 -j RETURN
    iptables -t mangle -A clash_mask -d 127.0.0.0/8 -j RETURN
    iptables -t mangle -A clash_mask -d 169.254.0.0/16 -j RETURN
    iptables -t mangle -A clash_mask -d 172.16.0.0/16 -j RETURN
    iptables -t mangle -A clash_mask -d 192.168.0.0/16 -j RETURN
    iptables -t mangle -A clash_mask -d 224.0.0.0/4 -j RETURN
    iptables -t mangle -A clash_mask -d 240.0.0.0/4 -j RETURN
    iptables -t mangle -A clash_mask -j RETURN -m mark --mark 0xff
    iptables -t mangle -A clash_mask -p udp -j MARK --set-mark 1
    iptables -t mangle -A clash_mask -p tcp -j MARK --set-mark 1
    iptables -t mangle -A OUTPUT -j clash_mask
}

stop_service(){
    local clash_mpid=""

    clash_mpid=$(ps -w | grep -w "/sbin/clash" | grep -v grep| awk '{print $1}')
    
    if [ "${clash_mpid}" != "" ]; then
        kill -9 ${clash_mpid}
    fi

    # Clean out PIDFile
    rm -f /var/run/clash.pid
    # Clean FWMARK
    ip rule del fwmark 1 table 100
    ip route del local 0.0.0.0/0 dev lo table 100
    # Delete Reference First
    iptables -t mangle -D PREROUTING -j clash
    iptables -t mangle -D OUTPUT -j clash_mask
    # Clear all rules
    iptables -t mangle -F clash_mask
    iptables -t mangle -F clash
    # Delete created chains
    iptables -t mangle -X clash_mask
    iptables -t mangle -X clash
}
